version: "3"
services:
  db:
    image: aa8y/postgres-dataset:world
  library:
    image: hiding_credentials_library
    build: ./library
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: db
      PGPORT: 5432
    ports:
        - "8270:8270"